Finally fixed the bot issues + potential fix for issue #8 (#59)
* Make it that the old start script can start centuria by adding a wrapper, with a warning tho. Also removed a very old datafixer.

* Missing changes my bad

* Some code cleanup (formatting)

* Sanc fixer for new members and those without sancs (lightweight)

* Fix typo

* Fix issue with changelogs

* Cleanup and such

* Ported all discord commands over, ported 1 game command over

* Implement more commands

* WIP quest manager

* Quick patch for the bot

* Another quick patch for the bot-

* Another quick patch for the bot-

* (Workaround) disable quest manager

* Increase version

* Fix for login issues

* Failsafe

* Fix

* Fixed command registration issue

* Disable command registration for testing purposes

* Add more logging

* Fix NoClassDefFoundError caused by refactor in the main server

* Fix for issues with the quest manager

* Fix issues with the chat server